module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      spacing: {
        100: '28rem',
        128: '32rem',
        156: '48rem',
      },
      fontFamily: {
        kaiseiopti: ['"Kaisei Opti"'],
        kaiseidecol: ['"Kaisei Decol"'],
        kaiseiharunoumi: ['"Kaisei HarunoUmi"'],
        kaiseitokumin: ['"Kaisei Tokumin"'],
        hinamincho: ['"Hina Mincho"'],
        kleeone: ['"Klee One"'],
        rampartone: ['"Rampart One"'],
        shipporimincho: ['"Shippori Mincho"'],
        sawarabigothic: ['"Sawarabi Gothic"'],
        sawarabimincho: ['"Sawarabi Mincho"'],
        newtegomin: ['"New Tegomin"'],
        kiwimaru: ['"Kiwi Maru"'],
        delagothicone: ['"Dela Gothic One"'],
        yomogi: ['"Yomogi"'],
        hachimarupop: ['"Hachi Maru Pop"'],
        pottaone: ['"Potta One"'],
        stick: ['"Stick"'],
        rocknrollone: ['"RocknRoll One"'],
        reggaeone: ['"Reggae One"'],
        trainone: ['"Train One"'],
        dotgothic16: ['"DotGothic16"'],
        yuseimagic: ['"Yusei Magic"'],
        kosugi: ['"Kosugi"'],
        kosugimaru: ['"Kosugi Maru"'],
        mplus1: ['"M PLUS 1"'],
        mplus2: ['"M PLUS 2"'],
        mplus1code: ['"M PLUS 1 Code"'],
        notosansjp: ['"Noto Sans JP"'],
        notoserifjp: ['"Noto Serif JP"'],
        zenantiquesoft: ['"Zen Antique Soft"'],
        murecho: ['"Murecho"'],
        mochiypopone: ['Mochiy Pop One'],
        yujisyuku: ['"Yuji Syuku"'],
        yujiboku: ['"Yuji Boku"'],
        yujimai: ['"Yuji Mai"'],
        zenkakugothicnew: ['"Zen Kaku Gothic New"'],
        zenmarugothic: ['"Zen Maru Gothic"'],
        zenkakugothicantique: ['"Zen Kaku Gothic Antique"'],
        zenoldmincho: ['"Zen Old Mincho"'],
        zenantique: ['"Zen Antique"'],
        zenkurenaido: ['"Zen Kurenaido"'],
        shipporiantique: ['"Shippori Antique"'],
        morisawabizudgothic: ['"BIZ UDGothic"'],
        morisawabizudmincho: ['"BIZ UDMincho"'],
        morisawabizudpmincho: ['"BIZ UDPMincho"'],
      },
      keyframes: {
        'fade-in-down': {
          '0%': {
            opacity: '0',
            transform: 'translateY(-10px)',
          },
          '100%': {
            opacity: '1',
            transform: 'translateY(0)',
          },
        },
        'fade-out-down': {
          from: {
            opacity: '1',
            transform: 'translateY(0px)',
          },
          to: {
            opacity: '0',
            transform: 'translateY(10px)',
          },
        },
        'fade-in-up': {
          '0%': {
            opacity: '0',
            transform: 'translateY(20px)',
          },
          '100%': {
            opacity: '1',
            transform: 'translateY(0)',
          },
        },
        'fade-out-up': {
          from: {
            opacity: '1',
            transform: 'translateY(0px)',
          },
          to: {
            opacity: '0',
            transform: 'translateY(10px)',
          },
        },
      },
      animation: {
        'fade-in-down': 'fade-in-down 0.5s ease-out',
        'fade-out-down': 'fade-out-down 0.5s ease-out',
        'fade-in-up': 'fade-in-up 0.5s ease-out',
        'fade-out-up': 'fade-out-up 0.5s ease-out',
      },
    },
  },
  plugins: [require('daisyui')],
}
