module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        kaiseiopti: ['"Kaisei Opti"'],
        kaiseidecol: ['"Kaisei Decol"'],
        kaiseiharunoumi: ['"Kaisei HarunoUmi"'],
        kaiseitokumin: ['"Kaisei Tokumin"'],
        hinamincho: ['"Hina Mincho"'],
        kleeone: ['"Klee One"'],
        rampartone: ['"Rampart One"'],
        shipporimincho: ['"Shippori Mincho"'],
        sawarabigothic: ['"Sawarabi Gothic"'],
        sawarabimincho: ['"Sawarabi Mincho"'],
        newtegomin: ['"New Tegomin"'],
        kiwimaru: ['"Kiwi Maru"'],
        delagothicone: ['"Dela Gothic One"'],
        yomogi: ['"Yomogi"'],
        hachimarupop: ['"Hachi Maru Pop"'],
        pottaone: ['"Potta One"'],
        stick: ['"Stick"'],
        rocknrollone: ['"RocknRoll One"'],
        reggaeone: ['"Reggae One"'],
        trainone: ['"Train One"'],
        dotgothic16: ['"DotGothic16"'],
        yuseimagic: ['"Yusei Magic"'],
        kosugi: ['"Kosugi"'],
        kosugimaru: ['"Kosugi Maru"'],
        mplus1: ['"M PLUS 1"'],
        mplus2: ['"M PLUS 2"'],
        mplus1code: ['"M PLUS 1 Code"'],
        notosansjp: ['"Noto Sans JP"'],
        notoserifjp: ['"Noto Serif JP"'],
        zenantiquesoft: ['"Zen Antique Soft"'],
        murecho: ['"Murecho"'],
        mochiypopone: ['Mochiy Pop One'],
        yujisyuku: ['"Yuji Syuku"'],
        yujiboku: ['"Yuji Boku"'],
        yujimai: ['"Yuji Mai"'],
        zenkakugothicnew: ['"Zen Kaku Gothic New"'],
        zenmarugothic: ['"Zen Maru Gothic"'],
        zenkakugothicantique: ['"Zen Kaku Gothic Antique"'],
        zenoldmincho: ['"Zen Old Mincho"'],
        zenantique: ['"Zen Antique"'],
        zenkurenaido: ['"Zen Kurenaido"'],
        shipporiantique: ['"Shippori Antique"'],
        morisawabizudgothic: ['"BIZ UDGothic"'],
        morisawabizudmincho: ['"BIZ UDMincho"'],
        morisawabizudpmincho: ['"BIZ UDPMincho"'],
      },
    },
  },
  plugins: [],
}
